version: "3.9"
services:
  db:
    image: postgres:15.2
    environment:
      - POSTGRES_PASSWORD=shhh
    ports:
      - "6432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  init:
    build: _init/
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://postgres:shhh@db:5432/postgres

  data-importer:
    build: data-importer/
    depends_on:
      init:
        condition: service_completed_successfully
    environment:
      - PORT=3000
      - DATABASE_URL=postgres://postgres:shhh@db:5432/postgres
    ports:
      - "3000:3000"

  data-service:
    build: data-service/
    depends_on:
      init:
        condition: service_completed_successfully
    environment:
      - PORT=4000
      - DATABASE_URL=postgres://postgres:shhh@db:5432/postgres
    ports:
      - "4000:4000"

  scoring-service:
    build: scoring-service/
    depends_on:
      init:
        condition: service_completed_successfully
      data-service:
        condition: service_started
    environment:
      - PORT=5000
      - DATA_SERVICE_URL=http://data-service:4000
    ports:
      - "5001:5000"
